# Generated by Django 2.0.6 on 2019-02-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_first_name', models.CharField(max_length=20)),
                ('citizen_last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='citizen_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models4app.State'),
        ),
    ]
